import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  note: [
    'note/introduction',
    {
      label: '计算机基础',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/computer-basic',
      },
      // items: [
      //   {
      //     type: 'autogenerated',
      //     dirName: 'note/001_计算机基础',
      //   },
      // ],
      // 这样写会为每个文件夹生成一个目录
      items: [
        {
          label: '编码基础',
          type: 'category',
          link: { 
            type: 'generated-index',
            slug: '/note/computer-basic/encoding-basic',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'note/001_计算机基础/编码基础',
            },
          ],
        },
        {
          label: '计算机网络',
          type: 'category',
          link: { 
            type: 'generated-index',
            slug: '/note/computer-basic/computer-network',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'note/001_计算机基础/计算机网络',
            },
          ],
        },
      ]
    },
    {
      label: '前端基础',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/frontend-basic',
      },
      // items: [
      //   {
      //     type: 'autogenerated',
      //     dirName: 'note/002_前端基础',
      //   },
      // ],
      items: [
        {
          label: 'HTML',
          type: 'category',
          link: { 
            type: 'generated-index',
            slug: '/note/frontend-basic/html',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'note/002_前端基础/001_HTML',
            },
          ],
        },
        {
          label: 'CSS',
          type: 'category',
          link: { 
            type: 'generated-index',
            slug: '/note/frontend-basic/css',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'note/002_前端基础/002_CSS',
            },
          ],
        },
        {
          label: 'Javascript',
          type: 'category',
          link: { 
            type: 'generated-index',
            slug: '/note/frontend-basic/javascript',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'note/002_前端基础/003_Javascript',
            },
          ],
        },
        {
          label: '网络安全',
          type: 'category',
          link: { 
            type: 'generated-index',
            slug: '/note/frontend-basic/security',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'note/002_前端基础/004_网络安全',
            },
          ],
        },
      ]
    },
    {
      label: 'NodeJS',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/nodejs',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/003_nodejs',
        },
      ],
    },
    {
      label: '前端工程化',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/frontend-engineering',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/004_前端工程化',
        },
      ],
    },
    {
      label: 'React',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/react',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/006_react',
        },
      ],
    },
    {
      label: '跨端开发',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/cross-platform-development',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/007_跨端开发',
        },
      ],
    },
    {
      label: '后端开发',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/backend-development',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/008_后端开发',
        },
      ],
    },
    {
      label: '解决方案',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/solution',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/009_解决方案',
        },
      ],
    },
    {
      label: '一句话笔记',
      type: 'category',
      link: { 
        type: 'generated-index',
        slug: '/note/one-sentence-note',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/999_一句话笔记',
        },
      ],
    }
  ],
  tools: [
  ],
}

module.exports = sidebars
